window.LANDYCISS_COLLECTIONS = {
  "new-drop": {
    kicker: "Nueva coleccion",
    title: "Nueva coleccion",
    description:
      "Mockups individuales de la nueva linea: apparel, accesorios, etiqueta, botella, bolso, campana y detalles premium.",
    board: "./mockups/board-new-drop.png",
    pieces: [
      ["Banner principal", "./mockups/collections/new-drop/00-new-collection-banner.png"],
      ["Launch poster", "./mockups/collections/new-drop/01-launch-poster.png"],
      ["Crewneck sweatshirt", "./mockups/collections/new-drop/02-crewneck-sweatshirt.png"],
      ["Rubber patch detail", "./mockups/collections/new-drop/03-rubber-patch-detail.png"],
      ["Performance leggings", "./mockups/collections/new-drop/04-performance-leggings.png"],
      ["Training shorts", "./mockups/collections/new-drop/05-training-shorts.png"],
      ["Training towel", "./mockups/collections/new-drop/06-training-towel.png"],
      ["Neck label + tag", "./mockups/collections/new-drop/07-neck-label-and-tag.png"],
      ["Wristbands", "./mockups/collections/new-drop/08-wristbands.png"],
      ["Performance socks", "./mockups/collections/new-drop/09-performance-socks.png"],
      ["Technical backpack", "./mockups/collections/new-drop/10-technical-backpack.png"],
      ["Cap", "./mockups/collections/new-drop/11-cap.png"],
      ["Duffle bag", "./mockups/collections/new-drop/12-duffle-bag.png"],
      ["Gym bottle", "./mockups/collections/new-drop/13-gym-bottle.png"],
      ["Hoodie back", "./mockups/collections/new-drop/14-hoodie-back.png"],
      ["Technical jacket", "./mockups/collections/new-drop/15-technical-jacket.png"],
      ["Match jersey", "./mockups/collections/new-drop/16-match-jersey.png"],
      ["Athlete shirt", "./mockups/collections/new-drop/17-athlete-shirt.png"],
    ],
  },
  "gemini-suite": {
    kicker: "Suite completa",
    title: "Galeria general LANDYCISS",
    description:
      "Una vista global con indumentaria, accesorios, packaging, social media y piezas de marca.",
    board: "./mockups/board-gemini-suite.png",
    pieces: [
      ["Shirt + hoodie", "./mockups/collections/gemini-suite/01-shirt-hoodie.png"],
      ["Athlete poster", "./mockups/collections/gemini-suite/02-athlete-poster.png"],
      ["Backpack", "./mockups/collections/gemini-suite/03-backpack.png"],
      ["Bottle + packaging", "./mockups/collections/gemini-suite/04-bottle-packaging.png"],
      ["Textile detail", "./mockups/collections/gemini-suite/05-textile-detail.png"],
      ["White polo", "./mockups/collections/gemini-suite/06-white-polo.png"],
      ["Social tablet", "./mockups/collections/gemini-suite/07-social-tablet.png"],
      ["Stationery", "./mockups/collections/gemini-suite/08-stationery.png"],
    ],
  },
  apparel: {
    kicker: "Indumentaria tecnica",
    title: "Apparel system",
    description:
      "Prendas principales, jersey, hoodie, shorts y detalles textiles para presentar la linea deportiva.",
    board: "./mockups/board-apparel-01.png",
    pieces: [
      ["Brand hero", "./mockups/collections/apparel/01-brand-hero.png"],
      ["Compression shirt", "./mockups/collections/apparel/02-compression-shirt.png"],
      ["Hoodie back", "./mockups/collections/apparel/03-hoodie-back.png"],
      ["Jacket front", "./mockups/collections/apparel/04-jacket-front.png"],
      ["Match jersey", "./mockups/collections/apparel/05-match-jersey.png"],
      ["Long sleeve", "./mockups/collections/apparel/06-long-sleeve.png"],
      ["Sweatshirt", "./mockups/collections/apparel/07-sweatshirt.png"],
      ["Shorts", "./mockups/collections/apparel/08-shorts.png"],
      ["Back shirt", "./mockups/collections/apparel/09-back-shirt.png"],
      ["Collar detail", "./mockups/collections/apparel/10-collar-detail.png"],
      ["Sleeve detail", "./mockups/collections/apparel/11-sleeve-detail.png"],
      ["Waist label", "./mockups/collections/apparel/12-waist-label.png"],
    ],
  },
  accessories: {
    kicker: "Accesorios y merch",
    title: "Training accessories",
    description:
      "Sistema de merchandising con bolso, botella, gorra, calcetas, etiquetas y texturas negras.",
    board: "./mockups/board-accessories-01.png",
    pieces: [
      ["Logo lockup", "./mockups/collections/accessories/01-logo-lockup.png"],
      ["Cap", "./mockups/collections/accessories/02-cap.png"],
      ["Rubber patch", "./mockups/collections/accessories/03-rubber-patch.png"],
      ["Duffle bag", "./mockups/collections/accessories/04-duffle-bag.png"],
      ["Bottle", "./mockups/collections/accessories/05-bottle.png"],
      ["Wristbands", "./mockups/collections/accessories/06-wristbands.png"],
      ["Socks", "./mockups/collections/accessories/07-socks.png"],
      ["Woven label", "./mockups/collections/accessories/08-woven-label.png"],
      ["Towel", "./mockups/collections/accessories/09-towel.png"],
      ["Backpack", "./mockups/collections/accessories/10-backpack.png"],
      ["Fabric tags", "./mockups/collections/accessories/11-fabric-tags.png"],
      ["Benefit strip", "./mockups/collections/accessories/12-bottom-brand-strip.png"],
    ],
  },
  campaign: {
    kicker: "Campana",
    title: "Launch campaign",
    description:
      "Piezas de lanzamiento para redes, posters, tarjetas, packaging y patron de marca.",
    board: "./mockups/board-campaign-01.png",
    pieces: [
      ["Victory poster", "./mockups/collections/campaign/01-victory-poster.png"],
      ["Social banner", "./mockups/collections/campaign/02-social-banner.png"],
      ["Launch card", "./mockups/collections/campaign/03-launch-card.png"],
      ["Runner ad", "./mockups/collections/campaign/04-runner-ad.png"],
      ["Business cards", "./mockups/collections/campaign/05-business-cards.png"],
      ["Packaging box", "./mockups/collections/campaign/06-packaging-box.png"],
      ["Pattern", "./mockups/collections/campaign/07-pattern.png"],
      ["Impact lockup", "./mockups/collections/campaign/08-impact-lockup.png"],
    ],
  },
  urban: {
    kicker: "Ropa deportiva urbana",
    title: "Urban performance",
    description:
      "Direccion visual nocturna con atleta, chaqueta tecnica, hoodie, poster urbano y detalles de material.",
    board: "./mockups/board-urban-01.png",
    pieces: [
      ["Night runner", "./mockups/collections/urban/01-night-runner.png"],
      ["Embroidered detail", "./mockups/collections/urban/02-embroidered-detail.png"],
      ["Hoodie back", "./mockups/collections/urban/03-hoodie-back.png"],
      ["Brand copy", "./mockups/collections/urban/04-brand-copy.png"],
      ["Wordmark panel", "./mockups/collections/urban/05-wordmark-panel.png"],
      ["Technical jacket", "./mockups/collections/urban/06-technical-jacket.png"],
      ["Street poster", "./mockups/collections/urban/07-street-poster.png"],
      ["Wall mark", "./mockups/collections/urban/08-wall-mark.png"],
      ["Label detail", "./mockups/collections/urban/09-label-detail.png"],
      ["Zipper detail", "./mockups/collections/urban/10-zipper-detail.png"],
    ],
  },
  "performance-kit": {
    kicker: "Performance kit",
    title: "Performance kit",
    description:
      "Bolso, mochila, gorra, botella, calcetas, toalla y etiquetas premium para mostrar el kit completo.",
    board: "./mockups/board-performance-01.png",
    pieces: [
      ["Brand panel", "./mockups/collections/performance-kit/01-brand-panel.png"],
      ["Cap", "./mockups/collections/performance-kit/02-cap.png"],
      ["Duffle bag", "./mockups/collections/performance-kit/03-duffle-bag.png"],
      ["Bottle", "./mockups/collections/performance-kit/04-bottle.png"],
      ["Wristbands", "./mockups/collections/performance-kit/05-wristbands.png"],
      ["Socks", "./mockups/collections/performance-kit/06-socks.png"],
      ["Towel", "./mockups/collections/performance-kit/07-towel.png"],
      ["Backpack front", "./mockups/collections/performance-kit/08-backpack-front.png"],
      ["Label grid", "./mockups/collections/performance-kit/09-label-grid.png"],
      ["Duffle in use", "./mockups/collections/performance-kit/10-duffle-in-use.png"],
      ["Benefit strip", "./mockups/collections/performance-kit/11-benefit-strip.png"],
    ],
  },
  engineered: {
    kicker: "Engineered excellence",
    title: "Engineered excellence",
    description:
      "Campana atletica de mayor energia con corredor, storytelling de logo, bordado, jersey y tags.",
    board: "./mockups/board-performance-02.png",
    pieces: [
      ["Runner campaign", "./mockups/collections/engineered/01-runner-campaign.png"],
      ["Logo story", "./mockups/collections/engineered/02-logo-story.png"],
      ["Embroidered closeup", "./mockups/collections/engineered/03-embroidered-closeup.png"],
      ["Rise beyond", "./mockups/collections/engineered/04-rise-beyond.png"],
      ["Hoodie night", "./mockups/collections/engineered/05-hoodie-night.png"],
      ["Accessory kit", "./mockups/collections/engineered/06-accessory-kit.png"],
      ["Performance label", "./mockups/collections/engineered/07-performance-label.png"],
      ["Technical jersey", "./mockups/collections/engineered/08-technical-jersey.png"],
      ["Tags and box", "./mockups/collections/engineered/09-tags-and-box.png"],
      ["Footer strip", "./mockups/collections/engineered/10-footer-strip.png"],
    ],
  },
};
